import type { Metadata } from "next";
import { Gochi_Hand } from 'next/font/google'
import "./globals.css";
import SideRail from "@/components/SideRail";


const gochiHand = Gochi_Hand({ 
  weight: '400', 
  subsets: ['latin'],
  variable: '--font-gochi' 
})


export const metadata: Metadata = {
  title: "Portfolio - B",
  description: "Generated by create next app",
};


export default function RootLayout({children}) {
  return (
    <html>
      <body>

      <SideRail position="left" />

        <main>{children}</main>      
      
      <SideRail position="right" />
        
        

      </body>
        
    </html>
  );
}


